# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # ルートのウェブサイトの依存関係をチェック
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "tar"
        update-types:
          - "minor"
          - "patch"

  # CLI とテンプレートの依存関係を一括チェック
  - package-ecosystem: "npm"
    directory: "/packages/nextjs-rich-tpl"
    schedule:
      interval: "daily"
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "tar"
        update-types:
          - "minor"
          - "patch"

  # テンプレートの依存関係を一括でチェック
  - package-ecosystem: "npm"
    directories:
      - "/examples/app/with-i18n-routing"
      - "/examples/app/without-i18n-routing"
    schedule:
      interval: "daily"
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "tar"
        update-types:
          - "minor"
          - "patch"
